development:
  google_maps_api_key: YOUR GOOGLE API KEY
  secret_token: rake secret

production:
  google_maps_api_key: <%= ENV['GOOGLE_MAPS_API_KEY'] %>
  secret_token: <%= ENV['SECRET_TOKEN'] %>

test:
  google_maps_api_key: YOUR GOOGLE API KEY
  secret_token: rake secret
