development:
  google_maps_api_key: YOUR GOOGLE API KEY
  secret_key_base: rake secret

production:
  google_maps_api_key: <%= ENV['GOOGLE_MAPS_API_KEY'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

test:
  google_maps_api_key: YOUR GOOGLE API KEY
  secret_key_base: rake secret
